[package]
name = "aoc-2015"
version = "0.1.0"
authors = ["Seth W <swidoff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
md5 = "0.7.0"
petgraph = "0.5.1"

